FROM python:3.12-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем только requirements.txt для установки зависимостей
COPY requirements.txt ./

# Устанавливаем зависимости из requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы из текущей директории в рабочую директорию контейнера
COPY . .

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 
